In [27]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score
from sklearn.linear_model import LogisticRegression

In [2]:
diabetes_data=pd.read_csv('diabetes.csv')

In [3]:
diabetes_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
diabetes_data.shape

(768, 9)

In [5]:
diabetes_data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
diabetes_data['Outcome'].value_counts()
#0 is non diabetics and 1 is diabetics

Outcome
0    500
1    268
Name: count, dtype: int64

In [7]:
diabetes_data.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [8]:
diabetes_data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
features=diabetes_data.drop(columns='Outcome',axis=1) #Droping the column
target=diabetes_data['Outcome']

In [10]:
print(features)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [11]:
print(target)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Data Standardization

In [12]:
scaler=StandardScaler()

In [13]:
scaler.fit(features)

StandardScaler()

In [14]:
standardised_data=scaler.transform(features)

In [15]:
standardised_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]], shape=(768, 8))

In [16]:
standardised_data=pd.DataFrame(standardised_data,columns=features.columns)

In [17]:
standardised_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.639947,0.848324,0.149641,0.907270,-0.692891,0.204013,0.468492,1.425995
1,-0.844885,-1.123396,-0.160546,0.530902,-0.692891,-0.684422,-0.365061,-0.190672
2,1.233880,1.943724,-0.263941,-1.288212,-0.692891,-1.103255,0.604397,-0.105584
3,-0.844885,-0.998208,-0.160546,0.154533,0.123302,-0.494043,-0.920763,-1.041549
4,-1.141852,0.504055,-1.504687,0.907270,0.765836,1.409746,5.484909,-0.020496
...,...,...,...,...,...,...,...,...
763,1.827813,-0.622642,0.356432,1.722735,0.870031,0.115169,-0.908682,2.532136
764,-0.547919,0.034598,0.046245,0.405445,-0.692891,0.610154,-0.398282,-0.531023
765,0.342981,0.003301,0.149641,0.154533,0.279594,-0.735190,-0.685193,-0.275760
766,-0.844885,0.159787,-0.470732,-1.288212,-0.692891,-0.240205,-0.371101,1.170732
767,-0.844885,-0.873019,0.046245,0.656358,-0.692891,-0.202129,-0.473785,-0.871374

In [18]:
np.round(standardised_data.describe(),1)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,768.0,768.0,768.0,768.0,768.0,768.0,768.0,768.0
mean,-0.0,-0.0,0.0,0.0,-0.0,0.0,0.0,0.0
std,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
min,-1.1,-3.8,-3.6,-1.3,-0.7,-4.1,-1.2,-1.0
25%,-0.8,-0.7,-0.4,-1.3,-0.7,-0.6,-0.7,-0.8
50%,-0.3,-0.1,0.1,0.2,-0.4,0.0,-0.3,-0.4
75%,0.6,0.6,0.6,0.7,0.4,0.6,0.5,0.7
max,3.9,2.4,2.7,4.9,6.7,4.5,5.9,4.1

In [19]:
X_train,X_test,Y_train,Y_test=train_test_split(standardised_data,target,test_size=0.2,random_state=2)

In [20]:
print(features.shape,X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(768, 8) (614, 8) (154, 8) (614,) (154,)

In [22]:
classifier=LogisticRegression()

In [23]:
classifier.fit(X_train,Y_train)

LogisticRegression()

In [24]:
X_train_prediction=classifier.predict(X_train)
training_data_accuracy=accuracy_score(Y_train,X_train_prediction)

In [25]:
print("AccuracyScore : ", training_data_accuracy)

AccuracyScore :  0.7801302931596091

In [29]:
X_test_prediction=classifier.predict(X_test)
testing_data_accuracy=accuracy_score(Y_test,X_test_prediction)

In [33]:
print("AccuracyScore of testdata : ", testing_data_accuracy)
print("confusion_matrix\n",confusion_matrix(Y_test,X_test_prediction))
print("Precision",precision_score(Y_test,X_test_prediction))

AccuracyScore of testdata :  0.7662337662337663
confusion_matrix
 [[96 13]
 [23 22]]
Precision 0.6285714285714286

In [36]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200)
rf.fit(X_train, Y_train)
X_test_pred1=rf.predict(X_test)
print("confusion_matrix\n",confusion_matrix(Y_test,X_test_pred1))
print("Precision",precision_score(Y_test,X_test_pred1))

confusion_matrix
 [[92 17]
 [20 25]]
Precision 0.5952380952380952

In [38]:
from sklearn.svm import SVC

svm = SVC(kernel='rbf')
svm.fit(X_train, Y_train)

X_test_pred2 = svm.predict(X_test)

print("confusion_matrix\n", confusion_matrix(Y_test, X_test_pred2))
print("Precision", precision_score(Y_test, X_test_pred2))

confusion_matrix
 [[93 16]
 [24 21]]
Precision 0.5675675675675675

In [30]:
input_data=(5,166,72,19,175,25.8,0.587,51)

input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
std_data=scaler.transform(input_data_reshaped)
print(std_data)
prediction=classifier.predict(std_data)
print(prediction)


if (prediction[0]==0):
    print("The person is not diabetic")
else:
    print("The person is diabetic")

[[ 0.3429808   1.41167241  0.14964075 -0.09637905  0.82661621 -0.78595734
   0.34768723  1.51108316]]
[1]
The person is diabetic

C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [39]:
import pickle

pickle.dump(classifier, open("diabetes_model.pkl","wb"))
pickle.dump(scaler, open("scaler.pkl","wb"))